# Generated by Django 4.0.4 on 2022-05-10 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to='news'),
        ),
    ]
