# Generated by Django 4.0.4 on 2022-05-10 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(max_length=255, upload_to=''),
        ),
    ]
